services:
  web:
    build: 
      context: .
      args:
        - DEV=true
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DATA_BASE_URL=${DATA_BASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    command: "flask run --debug --host 0.0.0.0 --port 5000"
