"""empty message

Revision ID: 933b5ed35523
Revises: a1067cad8aae
Create Date: 2025-03-06 22:11:00.784877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933b5ed35523'
down_revision = 'a1067cad8aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
